---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: latest

jenkins_connection_delay: 5
jenkins_connection_retries: 120
jenkins_home: /var/lib/jenkins
jenkins_hostname: 192.168.50.21
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins: [javadoc,bootstrap4-api,bootstrap5-api,jackson2-api,junit,echarts-api,token-macro,pipeline,pipeline-model-api,workflow-api,workflow-step-api,workflow-support,workflow-job,pipeline-model-definition,docker-commons,docker-workflow,workflow-multibranch,git,pipeline-github,github-branch-source,maven-plugin,timestamper,blueocean-bitbucket-pipeline,blueocean-commons,blueocean-config,blueocean-core-js,blueocean-dashboard,blueocean-events,blueocean-git-pipeline,blueocean-github-pipeline,blueocean-i18n,blueocean-jwt,blueocean-personalization,blueocean-pipeline-api-impl,blueocean-pipeline-editor,blueocean-rest-impl,blueocean-rest,blueocean-web,jenkins-design-language,blueocean-autofavorite,blueocean-display-url,pipeline-build-step,pipeline-milestone-step,blueocean-display-url,blueocean]
# jenkins_plugins: [{name: workflow-aggregator}, {name: git}]
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: yes
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
