# ---
# - name: Install Maven
#   apt: pkg=maven

# - name: Install unzip
#   apt: pkg=unzip

# - name: Download and unarchive maven
#   ansible.builtin.unarchive:
#     src: https://mirror.efect.ro/apache/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.zip
#     dest: /home/vagrant/
#     remote_src: yes


# - name: Update /etc/environment for newly maven app
#   lineinfile:
#     dest: /etc/environment
#     line: "export PATH=/home/vagrant/apache-maven-3.8.1/bin:$PATH"

vars:
  maven_version: 3.8.1
  maven_mirror: http://mirrors.m247.ro
  maven_archive: "apache-maven-{{ maven_version }}-bin.tar.gz"
  maven_url: "{{ maven_mirror }}/apache/maven/maven-3/{{ maven_version }}/binaries/{{ maven_archive }}"


- name: download and unarchive maven {{ maven_version }} - no copy
  unarchive:
    src: "{{ maven_url }}"
    dest: /opt
    copy: no
    creates: "/opt/apache-maven-{{ maven_version }}.zip"

- name: Create symlink for maven
  file:
    src: "/opt/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "/usr/bin/mvn"
    state: link